import { Level } from './src/core/level-progression.js';

/**
 * Word pool for the typing racer game
 * Words are organized by the adaptive difficulty system based on length
 */
const words: Level[] = [
	{ target: "köttur" },
	{ target: "hundur" },
	{ target: "bók" },
	{ target: "hestur" },
	{ target: "sól" },
	{ target: "vatn" },
	{ target: "eyja" },
	{ target: "fjall" },
	{ target: "ský" },
	{ target: "vinur" },
	{ target: "blóm" },
	{ target: "tré" },
	{ target: "rós" },
	{ target: "stjarna" },
	{ target: "tungl" },
	{ target: "hús" },
	{ target: "borð" },
	{ target: "stóll" },
	{ target: "gluggi" },
	{ target: "hurð" },
	{ target: "regnbogi" },
	{ target: "brauð" },
	{ target: "fiskur" },
	{ target: "fugl" },
	{ target: "strönd" },
	{ target: "sjór" },
	{ target: "ís" },
	{ target: "snjór" },
	{ target: "regn" },
	{ target: "vindur" },
	{ target: "þoka" },
	{ target: "morgunn" },
	{ target: "kvöld" },
	{ target: "nótt" },
	{ target: "dagur" },
	{ target: "sumar" },
	{ target: "vetur" },
	{ target: "haust" },
	{ target: "vor" },
	{ target: "hljómsveit" },
	{ target: "tónlist" },
	{ target: "dans" },
	{ target: "leikur" },
	{ target: "gleði" },
	{ target: "ást" },
	{ target: "friður" },
	{ target: "von" },
	{ target: "draumur" },
	{ target: "hamingja" },
	{ target: "flugvél" },
	{ target: "höfuður" },
	{ target: "bílar" },
	{ target: "kennari" },
	{ target: "stokkur" },
	{ target: "höfuðborg" },
	{ target: "barnabók" },
	{ target: "gluggatjöld" },
	{ target: "ástarsaga" },
	{ target: "málfræði" },
	{ target: "manneskja" },
	{ target: "græðlingur" },
	{ target: "sjúkrahús" },
	{ target: "tölvuleikur" },
	{ target: "aðferðafræði" },
	{ target: "menntaskóli" },
	{ target: "listrænt" },
	{ target: "kjallarinn" },
	{ target: "kappakstur" },
	{ target: "fjallatoppur" },
	{ target: "gott veður" },
	{ target: "fallegt land" },
	{ target: "kaldur vindur" },
	{ target: "hlýtt í dag" },
	{ target: "blátt ský" },
	{ target: "grænir dalir" },
	{ target: "djúpur sjór" },
	{ target: "há fjöll" },
	{ target: "gulur sandur" },
	{ target: "fögur náttúra" },
	{ target: "sætur köttur" },
	{ target: "stór hestur" },
	{ target: "lítill fugl" },
	{ target: "góður vinur" },
	{ target: "falleg rós" },
	{ target: "björt stjarna" },
	{ target: "hvítur snjór" },
	{ target: "rauður bíll" },
	{ target: "nýtt hús" },
	{ target: "gamalt tré" },
	{ target: "ég er hamingjusöm" },
	{ target: "veðrið er gott" },
	{ target: "sólin skín björt" },
	{ target: "tunglið er fullt" },
	{ target: "vindurinn blæs sterkt" },
	{ target: "hafið er blátt" },
	{ target: "fjöllin eru há" },
	{ target: "fuglinn syngur fallega" },
	{ target: "kötturinn sefur í sólinni" },
	{ target: "hesturinn hleypur hratt" },
	{ target: "börnin leika sér úti" },
	{ target: "ég elska Ísland" },
	{ target: "náttúran er undursamleg" },
	{ target: "regnboginn er litrík" },
	{ target: "morgunninn er fríður" },
	{ target: "kvöldið er kyrrt" },
	{ target: "sumarið er yndislegt" },
	{ target: "vetrarnóttin er löng" },
	{ target: "haustið er gylltur tími" },
	{ target: "vorið kemur með blómum" },
	{ target: "ég sé norðurljósin dansa" }
];

export default words;
